version: 2.1

executors:
  maven:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: /tmp/build

jobs:
  build:
    executor: maven
    steps:
      - checkout
      - run:
          name: Check POM
          command: mvn validate
  deploy:
    executor: maven
    steps:
      - attach_workspace:
          at: /tmp/build
      - restore_cache:
          key: parent-pom-{{ checksum "pom.xml" }}
      - run:
          name: Decrypt Signing Key
          command: openssl aes-256-cbc -S ${SIGN_ASC_SALT} -K ${SIGN_ASC_KEY} -iv ${SIGN_ASC_IV} -in .circleci/sign.asc.enc -out .circleci/sign.asc -d
      - run:
          name: Import Signing Key
          command: gpg --no-tty --batch --import .circleci/sign.asc
      - run:
          name: Deploy to Maven Central
          command: mvn deploy -s .circleci/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: parent-pom-{{ checksum "pom.xml" }}

workflows:
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
          context: deploy-maven
