name: CI Main

on:
  push:
    branches:
      - 'main'

jobs:
  package:

    runs-on: ubuntu-20.04

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: parent-pom-${{ hashFiles('**/pom.xml') }}
        restore-keys: parent-pom

    - name: Download Dependencies
      run: ./mvnw dependency:go-offline -U -B

    - name: Build with Maven
      run: ./mvnw validate -B

  deploy:
    needs: package

    runs-on: ubuntu-20.04

    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      GPG_KEY_BASE64: ${{ secrets.GPG_KEY_BASE64 }}
      GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Cache Maven package
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: parent-pom-${{ hashFiles('**/pom.xml') }}
        restore-keys: parent-pom

    - name: Import GPG key
      run: echo "${GPG_KEY_BASE64}" | base64 --decode | gpg --no-tty --batch --import

    - name: Publish
      run: |
        ./mvnw --batch-mode deploy \
          --settings ./.github/workflows/settings.xml \
          -P signing,deploying \
          -DskipTests=true
